"""Custom **exceptions** for LangChain.

All LangChain-specific exceptions inherit from :class:`LangChainException` so
callers can catch the full family with a single ``except LangChainException``
clause while still being able to narrow by sub-type when needed.

Error codes
-----------
Some exceptions embed a machine-readable :class:`ErrorCode` value in their
message (via :func:`create_message`).  The code is appended to the
troubleshooting URL so users can jump directly to the relevant documentation.
"""

from enum import Enum
from typing import Any


class LangChainException(Exception):  # noqa: N818
    """Base class for all LangChain-specific exceptions.

    Inheriting from this class lets callers catch any LangChain error with a
    single ``except LangChainException`` clause without suppressing unrelated
    exceptions from the Python standard library or third-party packages.
    """


class TracerException(LangChainException):
    """Raised by tracer implementations when recording a run fails."""


class OutputParserException(ValueError, LangChainException):  # noqa: N818
    """Raised by output parsers to signal a parsing error.

    This exception exists to distinguish parsing errors from other exceptions
    that may arise inside an output parser (e.g. network errors or assertion
    failures).  Downstream code — such as retry chains or agents — can catch
    :class:`OutputParserException` specifically and attempt to fix the output,
    while letting unexpected errors propagate normally.
    """

    def __init__(
        self,
        error: Any,
        observation: str | None = None,
        llm_output: str | None = None,
        send_to_llm: bool = False,  # noqa: FBT001,FBT002
    ):
        """Create an ``OutputParserException``.

        Args:
            error: The error that's being re-raised or an error message string.
                If a plain string is passed it is wrapped with a troubleshooting
                link via :func:`create_message`.
            observation: Human-readable explanation of what went wrong.  When
                *send_to_llm* is ``True`` this text is fed back to the model so
                it can attempt to correct its output.
            llm_output: The raw model output that failed to parse.  Sent back to
                the model alongside *observation* when *send_to_llm* is ``True``.
            send_to_llm: When ``True``, both *observation* and *llm_output* are
                attached to the exception so that an agent can include them in
                the next prompt.  Both arguments must be provided if this flag
                is set.

        Raises:
            ValueError: If *send_to_llm* is ``True`` but *observation* or
                *llm_output* is ``None``.
        """
        if isinstance(error, str):
            error = create_message(
                message=error, error_code=ErrorCode.OUTPUT_PARSING_FAILURE
            )

        super().__init__(error)
        if send_to_llm and (observation is None or llm_output is None):
            msg = (
                "Arguments 'observation' & 'llm_output'"
                " are required if 'send_to_llm' is True"
            )
            raise ValueError(msg)
        self.observation = observation
        self.llm_output = llm_output
        self.send_to_llm = send_to_llm


class ContextOverflowError(LangChainException):
    """Raised when the model's context window limit is exceeded.

    Chat model wrappers raise this exception when the number of input tokens
    exceeds the maximum context length supported by the model.  Callers can
    catch it to implement truncation, summarisation, or fallback strategies.
    """


class ErrorCode(Enum):
    """Machine-readable codes that identify the category of a LangChain error.

    Each code is appended to the troubleshooting URL generated by
    :func:`create_message` so users can navigate directly to the relevant
    documentation page.

    Attributes:
        INVALID_PROMPT_INPUT: The values supplied to fill a prompt template are
            invalid (e.g. wrong type, missing required variable).
        INVALID_TOOL_RESULTS: Tool results passed back to the model are
            malformed.  Defined for parity with the JS SDK.
        MESSAGE_COERCION_FAILURE: A value could not be coerced into a
            :class:`~langchain_core.messages.BaseMessage`.
        MODEL_AUTHENTICATION: API key or credential is missing or invalid.
            Defined for parity with the JS SDK.
        MODEL_NOT_FOUND: The requested model does not exist or is not
            accessible.  Defined for parity with the JS SDK.
        MODEL_RATE_LIMIT: The model provider returned a rate-limit response.
            Defined for parity with the JS SDK.
        OUTPUT_PARSING_FAILURE: An output parser could not parse the model's
            response into the expected structure.
    """

    INVALID_PROMPT_INPUT = "INVALID_PROMPT_INPUT"
    INVALID_TOOL_RESULTS = "INVALID_TOOL_RESULTS"  # Used in JS; not Py (yet)
    MESSAGE_COERCION_FAILURE = "MESSAGE_COERCION_FAILURE"
    MODEL_AUTHENTICATION = "MODEL_AUTHENTICATION"  # Used in JS; not Py (yet)
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"  # Used in JS; not Py (yet)
    MODEL_RATE_LIMIT = "MODEL_RATE_LIMIT"  # Used in JS; not Py (yet)
    OUTPUT_PARSING_FAILURE = "OUTPUT_PARSING_FAILURE"


def create_message(*, message: str, error_code: ErrorCode) -> str:
    """Build an error message that includes a link to the troubleshooting guide.

    Appends a URL constructed from *error_code* to *message* so that the
    resulting string, when used as an exception message, gives users a direct
    path to actionable documentation.

    Args:
        message: The human-readable description of the error.
        error_code: The :class:`ErrorCode` that categorises the error.  Its
            value is appended to the base documentation URL.

    Returns:
        A single string combining *message* and the troubleshooting URL.

    Example:
        .. code-block:: python

            create_message(
                message="Failed to parse output",
                error_code=ErrorCode.OUTPUT_PARSING_FAILURE,
            )
            # "Failed to parse output\nFor troubleshooting, visit: ..."
    """
    return (
        f"{message}\n"
        "For troubleshooting, visit: https://docs.langchain.com/oss/python/langchain"
        f"/errors/{error_code.value} "
    )
